// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: api/proto/dsp/v1/bid.proto

package dspv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 广告请求
type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 请求ID
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户ID
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`    // 设备ID
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`                                // IP地址
	AdSlots       []*AdSlot              `protobuf:"bytes,5,rep,name=ad_slots,json=adSlots,proto3" json:"ad_slots,omitempty"`       // 广告位列表
	Device        *DeviceInfo            `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`                        // 设备信息
	User          *UserInfo              `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`                            // 用户信息
	Version       string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`                      // 协议版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_api_proto_dsp_v1_bid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsp_v1_bid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dsp_v1_bid_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BidRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BidRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *BidRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BidRequest) GetAdSlots() []*AdSlot {
	if x != nil {
		return x.AdSlots
	}
	return nil
}

func (x *BidRequest) GetDevice() *DeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *BidRequest) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *BidRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 广告位信息
type AdSlot struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SlotId                 string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`                                                   // 广告位ID
	Width                  int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`                                                                  // 宽度
	Height                 int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`                                                                // 高度
	MinPrice               float64                `protobuf:"fixed64,4,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`                                           // 最低价格
	MaxPrice               float64                `protobuf:"fixed64,5,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`                                           // 最高价格
	Position               string                 `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`                                                             // 位置
	AdType                 string                 `protobuf:"bytes,7,opt,name=ad_type,json=adType,proto3" json:"ad_type,omitempty"`                                                   // 广告类型
	BidType                string                 `protobuf:"bytes,8,opt,name=bid_type,json=bidType,proto3" json:"bid_type,omitempty"`                                                // 计费类型(CPC/CPM)
	SupportedCreativeTypes []string               `protobuf:"bytes,9,rep,name=supported_creative_types,json=supportedCreativeTypes,proto3" json:"supported_creative_types,omitempty"` // 支持的创意类型
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdSlot) Reset() {
	*x = AdSlot{}
	mi := &file_api_proto_dsp_v1_bid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdSlot) ProtoMessage() {}

func (x *AdSlot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsp_v1_bid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdSlot.ProtoReflect.Descriptor instead.
func (*AdSlot) Descriptor() ([]byte, []int) {
	return file_api_proto_dsp_v1_bid_proto_rawDescGZIP(), []int{1}
}

func (x *AdSlot) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *AdSlot) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *AdSlot) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *AdSlot) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *AdSlot) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *AdSlot) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *AdSlot) GetAdType() string {
	if x != nil {
		return x.AdType
	}
	return ""
}

func (x *AdSlot) GetBidType() string {
	if x != nil {
		return x.BidType
	}
	return ""
}

func (x *AdSlot) GetSupportedCreativeTypes() []string {
	if x != nil {
		return x.SupportedCreativeTypes
	}
	return nil
}

// 设备信息
type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`                                   // 操作系统
	OsVersion     string                 `protobuf:"bytes,2,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`    // 系统版本
	Brand         string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`                             // 品牌
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`                             // 型号
	ScreenSize    string                 `protobuf:"bytes,5,opt,name=screen_size,json=screenSize,proto3" json:"screen_size,omitempty"` // 屏幕尺寸
	Carrier       string                 `protobuf:"bytes,6,opt,name=carrier,proto3" json:"carrier,omitempty"`                         // 运营商
	Connection    string                 `protobuf:"bytes,7,opt,name=connection,proto3" json:"connection,omitempty"`                   // 网络连接类型
	Idfa          string                 `protobuf:"bytes,8,opt,name=idfa,proto3" json:"idfa,omitempty"`                               // iOS广告标识符
	Imei          string                 `protobuf:"bytes,9,opt,name=imei,proto3" json:"imei,omitempty"`                               // 安卓设备标识符
	Oaid          string                 `protobuf:"bytes,10,opt,name=oaid,proto3" json:"oaid,omitempty"`                              // 安卓广告标识符
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_api_proto_dsp_v1_bid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsp_v1_bid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_dsp_v1_bid_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *DeviceInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *DeviceInfo) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *DeviceInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DeviceInfo) GetScreenSize() string {
	if x != nil {
		return x.ScreenSize
	}
	return ""
}

func (x *DeviceInfo) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *DeviceInfo) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *DeviceInfo) GetIdfa() string {
	if x != nil {
		return x.Idfa
	}
	return ""
}

func (x *DeviceInfo) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *DeviceInfo) GetOaid() string {
	if x != nil {
		return x.Oaid
	}
	return ""
}

// 用户信息
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Age           string                 `protobuf:"bytes,1,opt,name=age,proto3" json:"age,omitempty"`             // 年龄段
	Gender        string                 `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`       // 性别
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`           // 用户标签
	Interests     []string               `protobuf:"bytes,4,rep,name=interests,proto3" json:"interests,omitempty"` // 兴趣爱好
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`   // 地理位置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_api_proto_dsp_v1_bid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsp_v1_bid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_dsp_v1_bid_proto_rawDescGZIP(), []int{3}
}

func (x *UserInfo) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *UserInfo) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UserInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UserInfo) GetInterests() []string {
	if x != nil {
		return x.Interests
	}
	return nil
}

func (x *UserInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

// 广告响应
type BidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 请求ID
	Ads           []*AdResponse          `protobuf:"bytes,2,rep,name=ads,proto3" json:"ads,omitempty"`                              // 广告响应列表
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                      // 协议版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_api_proto_dsp_v1_bid_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsp_v1_bid_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dsp_v1_bid_proto_rawDescGZIP(), []int{4}
}

func (x *BidResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BidResponse) GetAds() []*AdResponse {
	if x != nil {
		return x.Ads
	}
	return nil
}

func (x *BidResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 单个广告响应
type AdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`                                                        // 广告位ID
	AdId          string                 `protobuf:"bytes,2,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`                                                              // 广告ID
	BidPrice      float64                `protobuf:"fixed64,3,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`                                                // 出价
	BidType       string                 `protobuf:"bytes,4,opt,name=bid_type,json=bidType,proto3" json:"bid_type,omitempty"`                                                     // 计费类型
	CreativeType  string                 `protobuf:"bytes,5,opt,name=creative_type,json=creativeType,proto3" json:"creative_type,omitempty"`                                      // 创意类型
	AdMarkup      string                 `protobuf:"bytes,6,opt,name=ad_markup,json=adMarkup,proto3" json:"ad_markup,omitempty"`                                                  // 广告标记
	LandingUrl    string                 `protobuf:"bytes,7,opt,name=landing_url,json=landingUrl,proto3" json:"landing_url,omitempty"`                                            // 落地页URL
	WinNotice     string                 `protobuf:"bytes,8,opt,name=win_notice,json=winNotice,proto3" json:"win_notice,omitempty"`                                               // 竞价获胜通知URL
	ClickNotice   string                 `protobuf:"bytes,9,opt,name=click_notice,json=clickNotice,proto3" json:"click_notice,omitempty"`                                         // 点击通知URL
	ImpNotice     []string               `protobuf:"bytes,10,rep,name=imp_notice,json=impNotice,proto3" json:"imp_notice,omitempty"`                                              // 展示通知URL列表
	Ext           map[string]string      `protobuf:"bytes,11,rep,name=ext,proto3" json:"ext,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 扩展字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdResponse) Reset() {
	*x = AdResponse{}
	mi := &file_api_proto_dsp_v1_bid_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdResponse) ProtoMessage() {}

func (x *AdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dsp_v1_bid_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdResponse.ProtoReflect.Descriptor instead.
func (*AdResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dsp_v1_bid_proto_rawDescGZIP(), []int{5}
}

func (x *AdResponse) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *AdResponse) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

func (x *AdResponse) GetBidPrice() float64 {
	if x != nil {
		return x.BidPrice
	}
	return 0
}

func (x *AdResponse) GetBidType() string {
	if x != nil {
		return x.BidType
	}
	return ""
}

func (x *AdResponse) GetCreativeType() string {
	if x != nil {
		return x.CreativeType
	}
	return ""
}

func (x *AdResponse) GetAdMarkup() string {
	if x != nil {
		return x.AdMarkup
	}
	return ""
}

func (x *AdResponse) GetLandingUrl() string {
	if x != nil {
		return x.LandingUrl
	}
	return ""
}

func (x *AdResponse) GetWinNotice() string {
	if x != nil {
		return x.WinNotice
	}
	return ""
}

func (x *AdResponse) GetClickNotice() string {
	if x != nil {
		return x.ClickNotice
	}
	return ""
}

func (x *AdResponse) GetImpNotice() []string {
	if x != nil {
		return x.ImpNotice
	}
	return nil
}

func (x *AdResponse) GetExt() map[string]string {
	if x != nil {
		return x.Ext
	}
	return nil
}

var File_api_proto_dsp_v1_bid_proto protoreflect.FileDescriptor

const file_api_proto_dsp_v1_bid_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/dsp/v1/bid.proto\x12\x06dsp.v1\"\x88\x02\n" +
	"\n" +
	"BidRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12)\n" +
	"\bad_slots\x18\x05 \x03(\v2\x0e.dsp.v1.AdSlotR\aadSlots\x12*\n" +
	"\x06device\x18\x06 \x01(\v2\x12.dsp.v1.DeviceInfoR\x06device\x12$\n" +
	"\x04user\x18\a \x01(\v2\x10.dsp.v1.UserInfoR\x04user\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\"\x93\x02\n" +
	"\x06AdSlot\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1b\n" +
	"\tmin_price\x18\x04 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x05 \x01(\x01R\bmaxPrice\x12\x1a\n" +
	"\bposition\x18\x06 \x01(\tR\bposition\x12\x17\n" +
	"\aad_type\x18\a \x01(\tR\x06adType\x12\x19\n" +
	"\bbid_type\x18\b \x01(\tR\abidType\x128\n" +
	"\x18supported_creative_types\x18\t \x03(\tR\x16supportedCreativeTypes\"\xfe\x01\n" +
	"\n" +
	"DeviceInfo\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x02 \x01(\tR\tosVersion\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x1f\n" +
	"\vscreen_size\x18\x05 \x01(\tR\n" +
	"screenSize\x12\x18\n" +
	"\acarrier\x18\x06 \x01(\tR\acarrier\x12\x1e\n" +
	"\n" +
	"connection\x18\a \x01(\tR\n" +
	"connection\x12\x12\n" +
	"\x04idfa\x18\b \x01(\tR\x04idfa\x12\x12\n" +
	"\x04imei\x18\t \x01(\tR\x04imei\x12\x12\n" +
	"\x04oaid\x18\n" +
	" \x01(\tR\x04oaid\"\x82\x01\n" +
	"\bUserInfo\x12\x10\n" +
	"\x03age\x18\x01 \x01(\tR\x03age\x12\x16\n" +
	"\x06gender\x18\x02 \x01(\tR\x06gender\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1c\n" +
	"\tinterests\x18\x04 \x03(\tR\tinterests\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\"l\n" +
	"\vBidResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12$\n" +
	"\x03ads\x18\x02 \x03(\v2\x12.dsp.v1.AdResponseR\x03ads\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x9d\x03\n" +
	"\n" +
	"AdResponse\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x13\n" +
	"\x05ad_id\x18\x02 \x01(\tR\x04adId\x12\x1b\n" +
	"\tbid_price\x18\x03 \x01(\x01R\bbidPrice\x12\x19\n" +
	"\bbid_type\x18\x04 \x01(\tR\abidType\x12#\n" +
	"\rcreative_type\x18\x05 \x01(\tR\fcreativeType\x12\x1b\n" +
	"\tad_markup\x18\x06 \x01(\tR\badMarkup\x12\x1f\n" +
	"\vlanding_url\x18\a \x01(\tR\n" +
	"landingUrl\x12\x1d\n" +
	"\n" +
	"win_notice\x18\b \x01(\tR\twinNotice\x12!\n" +
	"\fclick_notice\x18\t \x01(\tR\vclickNotice\x12\x1d\n" +
	"\n" +
	"imp_notice\x18\n" +
	" \x03(\tR\timpNotice\x12-\n" +
	"\x03ext\x18\v \x03(\v2\x1b.dsp.v1.AdResponse.ExtEntryR\x03ext\x1a6\n" +
	"\bExtEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012E\n" +
	"\n" +
	"BidService\x127\n" +
	"\n" +
	"ProcessBid\x12\x12.dsp.v1.BidRequest\x1a\x13.dsp.v1.BidResponse\"\x00B#Z!simple-dsp/api/proto/dsp/v1;dspv1b\x06proto3"

var (
	file_api_proto_dsp_v1_bid_proto_rawDescOnce sync.Once
	file_api_proto_dsp_v1_bid_proto_rawDescData []byte
)

func file_api_proto_dsp_v1_bid_proto_rawDescGZIP() []byte {
	file_api_proto_dsp_v1_bid_proto_rawDescOnce.Do(func() {
		file_api_proto_dsp_v1_bid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_dsp_v1_bid_proto_rawDesc), len(file_api_proto_dsp_v1_bid_proto_rawDesc)))
	})
	return file_api_proto_dsp_v1_bid_proto_rawDescData
}

var file_api_proto_dsp_v1_bid_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_dsp_v1_bid_proto_goTypes = []any{
	(*BidRequest)(nil),  // 0: dsp.v1.BidRequest
	(*AdSlot)(nil),      // 1: dsp.v1.AdSlot
	(*DeviceInfo)(nil),  // 2: dsp.v1.DeviceInfo
	(*UserInfo)(nil),    // 3: dsp.v1.UserInfo
	(*BidResponse)(nil), // 4: dsp.v1.BidResponse
	(*AdResponse)(nil),  // 5: dsp.v1.AdResponse
	nil,                 // 6: dsp.v1.AdResponse.ExtEntry
}
var file_api_proto_dsp_v1_bid_proto_depIdxs = []int32{
	1, // 0: dsp.v1.BidRequest.ad_slots:type_name -> dsp.v1.AdSlot
	2, // 1: dsp.v1.BidRequest.device:type_name -> dsp.v1.DeviceInfo
	3, // 2: dsp.v1.BidRequest.user:type_name -> dsp.v1.UserInfo
	5, // 3: dsp.v1.BidResponse.ads:type_name -> dsp.v1.AdResponse
	6, // 4: dsp.v1.AdResponse.ext:type_name -> dsp.v1.AdResponse.ExtEntry
	0, // 5: dsp.v1.BidService.ProcessBid:input_type -> dsp.v1.BidRequest
	4, // 6: dsp.v1.BidService.ProcessBid:output_type -> dsp.v1.BidResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_dsp_v1_bid_proto_init() }
func file_api_proto_dsp_v1_bid_proto_init() {
	if File_api_proto_dsp_v1_bid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_dsp_v1_bid_proto_rawDesc), len(file_api_proto_dsp_v1_bid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_dsp_v1_bid_proto_goTypes,
		DependencyIndexes: file_api_proto_dsp_v1_bid_proto_depIdxs,
		MessageInfos:      file_api_proto_dsp_v1_bid_proto_msgTypes,
	}.Build()
	File_api_proto_dsp_v1_bid_proto = out.File
	file_api_proto_dsp_v1_bid_proto_goTypes = nil
	file_api_proto_dsp_v1_bid_proto_depIdxs = nil
}
